networks:
  database:
    driver: bridge

services:
  django:
    build:
      target: production
    restart: on-failure
    networks:
      - database
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./collected_static:/django/collected_static
      - ./private_media:/django/private_media
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               uwsgi --http 0.0.0.0:8080 --processes 2 --threads 2 --chdir /django/ --wsgi-file ./config/wsgi.py"
    ports:
      - "8080:8080"

  database:
    image: mariadb:11.2.2-jammy
    restart: on-failure
    networks:
      - database
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_DATABASE=${DATABASE_NAME}
      - MARIADB_CHARACTER_SET_SERVER=utf8mb4
      - MARIADB_COLLATION_SERVER=utf8mb4_ja_0900_as_cs_ks
    volumes:
      - ./mariadb:/var/lib/mysql
