volumes:
  zoomail_database_data:
  zoomail_static_files:

networks:
  database:
    driver: bridge
  nginx:
    driver: bridge

services:
  django:
    build:
      target: production
    networks:
      - database
      - nginx
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - zoomail_static_files:/django/collected_static
    command: >
      bash -c "python manage.py collectstatic --noinput &&
               python manage.py migrate &&
               uwsgi --http 0.0.0.0:8080 --chdir /django/ --wsgi-file ./cpmap/wsgi.py"
    ports: []

  database:
    image: mariadb:11.2.2-jammy
    restart: on-failure
    networks:
      - database
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}
      - MARIADB_USER=${DATABASE_USER}
      - MARIADB_DATABASE=${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - zoomail_database_data:/var/lib/mysql:Z


  nginx:
    image: nginx:alpine-slim
    restart: on-failure
    depends_on:
      - django
    networks:
      - nginx
    volumes:
      - zoomail_static_files:/var/www/html/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/server.crt:/etc/nginx/conf.d/cert/server.crt
      - ./nginx/private.key:/etc/nginx/conf.d/cert/private.key
      - ./nginx/.well-known:/var/www/html/.well-known
    ports:
      - 80:80
      - 443:443
