# Generated by Django 2.0.13 on 2019-08-25 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kansouyoushi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.CharField(max_length=200, verbose_name='ライブ名')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='その他特記事項')),
                ('numbering', models.IntegerField(default=1, verbose_name='ナンバリング')),
                ('file', private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='kansoyoshi/%Y/', verbose_name='PDFファイル')),
                ('performed_at', models.DateField(verbose_name='ライブ日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kansou_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
