# Generated by Django 3.2.6 on 2021-10-01 23:42

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kansouyoushi',
            name='detail',
            field=models.CharField(blank=True, help_text='「2回生の分のみ」など', max_length=200, verbose_name='その他特記事項'),
        ),
        migrations.AlterField(
            model_name='kansouyoushi',
            name='file',
            field=private_storage.fields.PrivateFileField(help_text='おおむね10MB以下にしてください。大きいファイルの場合は分割してください。', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='kansoyoshi/%Y/', verbose_name='PDFファイル'),
        ),
        migrations.AlterField(
            model_name='kansouyoushi',
            name='numbering',
            field=models.IntegerField(default=1, help_text='ファイルが大きくなり、分割したときに〇〇ライブ1, 〇〇ライブ2という風に区切ってください。<br>特になければ1にしてください。', verbose_name='ナンバリング'),
        ),
    ]
