# Generated by Django 5.1.4 on 2025-03-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kansouyoushi',
            options={'verbose_name': '感想用紙', 'verbose_name_plural': '感想用紙'},
        ),
    ]
