# Generated by Django 3.2.14 on 2023-05-27 15:50

from django.db import migrations
import kansou.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0002_auto_20211121_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kansouyoushi',
            name='file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=kansou.models.kansou_upload_to, verbose_name='PDFファイル'),
        ),
    ]
