# Generated by Django 2.2.2 on 2019-08-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0002_auto_20190823_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kansouyoushi',
            name='live',
            field=models.CharField(max_length=200),
        ),
    ]
