# Generated by Django 2.2.2 on 2019-08-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0003_auto_20190823_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kansouyoushi',
            name='title',
        ),
    ]
