# Generated by Django 2.2.2 on 2019-08-24 20:35

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('kansou', '0005_auto_20190824_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kansouyoushi',
            name='file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='kansoyoshi/%Y/', verbose_name='PDFファイル'),
        ),
    ]
