# Generated by Django 2.2.2 on 2019-09-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('url', models.URLField(blank=True, verbose_name='アルバムのURL')),
                ('held_at', models.DateField(verbose_name='イベントを行った日')),
                ('thumbnail', private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='album_one_image/%Y', verbose_name='サムネイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
