# Generated by Django 2.2.2 on 2019-09-09 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='説明（あれば）')),
                ('url', models.URLField(blank=True, verbose_name='アルバムのURL')),
                ('held_at', models.DateField(verbose_name='イベントを行った日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
