# Generated by Django 2.2.2 on 2019-09-18 17:21

from django.db import migrations
import pictures.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=pictures.models.custom_upload_to, verbose_name='サムネイル'),
        ),
    ]
