# Generated by Django 2.2.2 on 2019-09-11 21:24

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='private_media', verbose_name='サムネイル'),
        ),
    ]
