# Generated by Django 2.2.2 on 2019-09-11 21:30

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20190911_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='album_one_image', verbose_name='サムネイル'),
        ),
    ]
