# Generated by Django 2.2.2 on 2019-09-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20190911_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='detail',
        ),
    ]
