# Generated by Django 2.2.2 on 2019-08-03 23:30

from django.db import migrations, models
import django.utils.timezone
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='song_num',
        ),
        migrations.AlterField(
            model_name='performance',
            name='recorded_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='music/%Y/%m/%d'),
        ),
    ]
