# Generated by Django 2.2.2 on 2019-09-18 17:28

from django.db import migrations
import player.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=player.models.custom_upload_to),
        ),
    ]
