# Generated by Django 2.2.2 on 2020-04-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_song_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
