# Generated by Django 2.2.4 on 2020-04-30 19:59

from django.db import migrations, models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('otherdocs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='詳細事項'),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='others/', verbose_name='ファイル'),
        ),
    ]
