# Generated by Django 2.2.4 on 2020-05-02 10:36

from django.db import migrations, models
import otherdocs.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('otherdocs', '0002_auto_20200430_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=otherdocs.models.custom_upload_to, verbose_name='ファイル'),
        ),
        migrations.AlterField(
            model_name='content',
            name='index',
            field=models.IntegerField(blank=True, default=0, help_text='ページ内での表示順です。初期値は「0」で、大きいほど上に、小さいほど(負の整数も可)下に表示されます。'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
