# Generated by Django 2.2.4 on 2021-02-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0003_auto_20210224_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashe',
            name='room',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
