# Generated by Django 2.2.4 on 2021-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_room', '0004_auto_20210225_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashe',
            name='event_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
