# Generated by Django 2.2.2 on 2019-10-19 03:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='曲名・バンド名・イベント名')),
                ('text', models.CharField(blank=True, max_length=400, verbose_name='説明')),
                ('days_begin', models.DateField(default=datetime.date(2019, 10, 19), verbose_name='開始日')),
                ('days_end', models.DateField(default=datetime.date(2019, 12, 18), verbose_name='終了日')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starttime', models.PositiveSmallIntegerField()),
                ('duration', models.IntegerField(default=30)),
                ('canattend', models.BooleanField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_schedule', to='awase.Calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollectHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('hour_begin', models.PositiveSmallIntegerField(default=9, verbose_name='開始時間')),
                ('hour_end', models.PositiveSmallIntegerField(default=26, verbose_name='終了時間')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_hour', to='awase.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_content', to='awase.Calendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
