# Generated by Django 2.2.2 on 2019-10-11 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.date(2019, 10, 11)),
        ),
        migrations.AddField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.date(2020, 1, 19)),
        ),
    ]
