# Generated by Django 2.2.2 on 2020-02-29 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='canattend',
            new_name='can_attend',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
