# Generated by Django 2.2.2 on 2019-10-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='starttime',
            field=models.DateTimeField(),
        ),
    ]
