# Generated by Django 2.2.4 on 2019-12-13 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0002_auto_20191019_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2019, 12, 13, 12, 35, 36, 284343), verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 2, 11, 12, 35, 36, 284343), verbose_name='終了日'),
        ),
    ]
