# Generated by Django 2.2.4 on 2020-01-17 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0003_auto_20191213_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2020, 1, 17, 13, 36, 51, 384705), verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 13, 36, 51, 384705), verbose_name='終了日'),
        ),
    ]
