# Generated by Django 2.2.2 on 2019-10-11 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0004_auto_20191011_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 1, 5, 46, 313469)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 1, 5, 46, 313469)),
        ),
    ]
