# Generated by Django 2.2.4 on 2020-01-18 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0004_auto_20200117_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='invite_key',
            field=models.CharField(default='password', max_length=32, verbose_name='招待用パスワード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2020, 1, 18, 17, 28, 26, 727449), verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 3, 18, 17, 28, 26, 727449), verbose_name='終了日'),
        ),
    ]
