# Generated by Django 2.2.4 on 2020-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0005_auto_20200118_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='invite_key',
            field=models.CharField(max_length=32, unique=True, verbose_name='招待用パスワード'),
        ),
    ]
