# Generated by Django 2.2.2 on 2020-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0006_auto_20200118_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='canattend',
            field=models.NullBooleanField(),
        ),
    ]
