# Generated by Django 2.2.2 on 2019-10-11 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0007_auto_20191011_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 1, 12, 26, 666037)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 1, 12, 26, 666037)),
        ),
    ]
