# Generated by Django 2.2.2 on 2020-02-22 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0007_auto_20200213_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendaruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
