# Generated by Django 2.2.2 on 2020-02-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0008_calendaruser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaruser',
            old_name='created_at',
            new_name='joined_at',
        ),
    ]
