# Generated by Django 2.2.2 on 2019-10-11 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0008_auto_20191011_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='text',
            field=models.CharField(blank=True, max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.datetime(2019, 10, 11, 2, 12, 28, 138077)),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.datetime(2020, 1, 19, 2, 12, 28, 138077)),
        ),
    ]
