# Generated by Django 2.2.2 on 2019-10-18 01:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0010_auto_20191011_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.date(2019, 10, 18), verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.date(2019, 12, 17), verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='text',
            field=models.CharField(blank=True, max_length=400, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=200, verbose_name='曲名・バンド名・イベント名'),
        ),
        migrations.CreateModel(
            name='CollectHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('hour_begin', models.PositiveSmallIntegerField(default=9, verbose_name='開始時間')),
                ('hour_end', models.PositiveSmallIntegerField(default=26, verbose_name='終了時間')),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_hour', to='awase.Calendar')),
            ],
        ),
    ]
