# Generated by Django 2.2.2 on 2019-10-19 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awase', '0011_auto_20191018_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendaruser',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='collecthour',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='calender',
            new_name='calendar',
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_begin',
            field=models.DateField(default=datetime.date(2019, 10, 19), verbose_name='開始日'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='days_end',
            field=models.DateField(default=datetime.date(2019, 12, 18), verbose_name='終了日'),
        ),
    ]
