# Generated by Django 3.2.6 on 2021-09-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialPage',
        ),
    ]
