# Generated by Django 3.2.6 on 2021-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_specialpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('genre', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
