# Generated by Django 5.1.4 on 2025-03-16 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('url', models.CharField(blank=True, max_length=2000, verbose_name='Youtubeの再生URL')),
                ('textcontent', models.TextField(blank=True, max_length=2000, verbose_name='テキスト')),
                ('held_at', models.DateField(verbose_name='イベントを行った日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
