# Generated by Django 5.1.4 on 2025-03-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubeurl',
            options={'verbose_name': 'Youtube動画', 'verbose_name_plural': 'Youtube動画'},
        ),
    ]
