# Generated by Django 2.2.2 on 2019-09-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190916_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeurl',
            name='listid',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtubeの再生リストID'),
        ),
    ]
