# Generated by Django 2.2.4 on 2021-03-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190916_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeurl',
            name='listid',
        ),
        migrations.AddField(
            model_name='youtubeurl',
            name='url',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Youtubeの再生URL'),
        ),
    ]
