# Generated by Django 2.2.2 on 2019-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttest',
            name='content',
            field=models.TextField(),
        ),
    ]
