# Generated by Django 2.2.2 on 2020-03-09 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0007_remove_kidoku_have_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='受信用メールアドレス')),
                ('year', models.IntegerField(verbose_name='入部年度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mail_address_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_message_id', models.CharField(editable=False, max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='送信時メールアドレス')),
                ('Requested', models.BooleanField(default=False, verbose_name='SendGridへ転送')),
                ('Processed', models.BooleanField(default=False, verbose_name='SendGridから送信')),
                ('Delivered', models.BooleanField(default=False, verbose_name='相手サーバーに到達')),
                ('Opened', models.BooleanField(default=False, verbose_name='開封')),
                ('Error_occurd', models.BooleanField(default=False, verbose_name='エラー')),
                ('Error_detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='エラー詳細')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_message_id', to='board.Message')),
            ],
        ),
    ]
