# Generated by Django 5.1.4 on 2024-12-18 21:42

import django.db.models.deletion
import django.utils.timezone
import mail.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_message', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'メーリス',
                'verbose_name_plural': 'メーリス',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_file', private_storage.fields.PrivateFileField(blank=True, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=mail.models.custom_upload_to)),
                ('org_filename', models.CharField(max_length=200)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='mail.message')),
            ],
        ),
        migrations.CreateModel(
            name='ToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, help_text='ここに表示名(ex「全回メーリス」)を指定すると、選択肢としてこの表示名が表示されます。指定がなければ「2018 24期」のように表示されます。', max_length=40, null=True, verbose_name='表示名')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_kaichou', to=settings.AUTH_USER_MODEL, verbose_name='会長')),
            ],
            options={
                'verbose_name': '宛先グループ',
                'verbose_name_plural': '宛先グループ',
            },
        ),
    ]
