# Generated by Django 5.1.4 on 2024-12-23 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_groups',
            field=models.ManyToManyField(related_name='messages', to='mail.togroup'),
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='送信時メールアドレス')),
                ('send_server', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sendgrid'), (2, 'Ses')], null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('error', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='mail.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MessageYear',
        ),
    ]
