# Generated by Django 5.1.4 on 2025-01-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_message_to_groups_maillog_delete_messageyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment_file',
            new_name='file',
        ),
    ]
