# Generated by Django 3.2.6 on 2021-10-01 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_delete_kidoku'),
        ('mail', '0002_auto_20200818_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocess',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='board.message'),
        ),
    ]
