# Generated by Django 3.2.6 on 2022-01-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_rename_to_togroup'),
        ('mail', '0003_alter_messageprocess_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageprocess',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='board.message'),
        ),
    ]
