# Generated by Django 3.2.14 on 2024-01-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0011_auto_20230527_1550'),
        ('mail', '0004_alter_messageprocess_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='送信時メールアドレス')),
                ('send_server', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sendgrid'), (2, 'Ses')], null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('error', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='board.message')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
