# Generated by Django 5.1.4 on 2025-03-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_rename_uploaded_at_file_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
