# Generated by Django 5.1.4 on 2025-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_alter_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
