# Generated by Django 5.1.4 on 2025-03-17 22:25

import django.db.models.deletion
import photo.models
import private_storage.fields
import private_storage.storage.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('url', models.URLField(blank=True, verbose_name='アルバムのURL')),
                ('held_at', models.DateField(verbose_name='イベントを行った日')),
                ('thumbnail', private_storage.fields.PrivateFileField(blank=True, help_text='JPEGファイルのみ対応しています。<br>5kB以上のファイルをアップロードすると自動的に縮小されます。', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=photo.models.custom_upload_to, verbose_name='サムネイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
