# Generated by Django 5.1.4 on 2025-03-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoalbum',
            options={'verbose_name': 'アルバム', 'verbose_name_plural': 'アルバム'},
        ),
    ]
