# Generated by Django 2.2.2 on 2019-08-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='furigana',
            field=models.CharField(default='', max_length=255),
        ),
    ]
