# Generated by Django 2.2.2 on 2019-10-19 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpmember',
            name='furigana',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ふりがなは全角ひらがなのみで入力してください。', regex='^[ぁ-ん]+$')]),
        ),
    ]
