# Generated by Django 2.2.2 on 2019-07-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_account',
            new_name='g_account',
        ),
    ]
