# Generated by Django 5.1.4 on 2025-03-16 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Emailアドレス')),
                ('year', models.IntegerField(help_text='2024年4月入部の場合、2024を入力してください。', verbose_name='入部年度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='招待者')),
            ],
            options={
                'verbose_name': 'ユーザー招待',
                'verbose_name_plural': 'ユーザー招待一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
