# Generated by Django 2.2.2 on 2019-08-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_furigana'),
        ('members', '0003_tmpmember'),
    ]

    operations = [
    ]
