# Generated by Django 2.2.2 on 2019-11-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_receive_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='receive_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='受信用メールアドレス'),
        ),
    ]
