# Generated by Django 2.2.2 on 2019-08-21 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_merge_20190819_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Googleアカウント'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='user',
            name='furigana',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='ふりがなは全角ひらがなのみで入力してください。', regex='^[ぁ-ん]+$')], verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='名字'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(verbose_name='入部年度'),
        ),
    ]
