# Generated by Django 2.2.2 on 2020-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_user_send_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_mail',
            field=models.BooleanField(default=True, verbose_name='メーリスを受信する'),
        ),
    ]
