# Generated by Django 2.2.2 on 2020-03-31 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200309_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='送信したメールアドレス')),
                ('sent_at', models.DateTimeField()),
                ('x_message_id', models.CharField(editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
