# Generated by Django 2.2.4 on 2020-08-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_testmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Emailアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='furigana',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.RegexValidator(message='ふりがなは全角ひらがなのみで入力してください。', regex='^[ぁ-んー]+$')], verbose_name='ふりがな'),
        ),
    ]
