# Generated by Django 2.2.4 on 2021-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200805_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='livelog_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Livelogメールアドレス'),
        ),
    ]
