# Generated by Django 3.2.6 on 2021-09-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_user_livelog_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TmpMember',
        ),
        migrations.AddField(
            model_name='user',
            name='google_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='livelog_login',
            field=models.BooleanField(default=False),
        ),
    ]
