# Generated by Django 2.2.2 on 2019-07-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('attachment', models.BooleanField(default=False)),
                ('sender_id', models.IntegerField()),
                ('writer_id', models.IntegerField()),
                ('created_at', models.DateTimeField(unique=True)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mes_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('mes_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages')),
            ],
        ),
        migrations.CreateModel(
            name='Message_Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='')),
                ('mes_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages')),
            ],
        ),
    ]
