# Generated by Django 2.2.2 on 2019-08-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='writer_id',
            new_name='writer',
        ),
    ]
