# Generated by Django 2.2.2 on 2019-06-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_attachment',
            name='mes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages'),
        ),
        migrations.AlterField(
            model_name='message_tag',
            name='mes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages'),
        ),
        migrations.AlterField(
            model_name='message_year',
            name='mes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages'),
        ),
    ]
