# Generated by Django 2.2.1 on 2019-07-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190712_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='newmessage',
            new_name='message',
        ),
    ]
