# Generated by Django 2.2.2 on 2019-07-10 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190710_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='sender',
            new_name='sender_id',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='writer',
            new_name='writer_id',
        ),
        migrations.AlterField(
            model_name='message_year',
            name='mes_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Messages'),
        ),
    ]
