# Generated by Django 2.2.1 on 2019-07-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190712_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='all',
        ),
    ]
