# Generated by Django 2.0.13 on 2019-06-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190621_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTest',
        ),
    ]
