# Generated by Django 2.2.2 on 2019-07-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190716_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='attachment_file',
        ),
    ]
