# Generated by Django 2.2.2 on 2019-08-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190710_2204'),
        ('board', '0006_auto_20190716_1715'),
    ]

    operations = [
    ]
