# Generated by Django 2.2.2 on 2019-11-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20191107_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidoku',
            name='have_read',
        ),
    ]
