# Generated by Django 2.2.4 on 2021-02-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_remove_kidoku_have_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kidoku',
        ),
    ]
