# Generated by Django 3.2.6 on 2021-09-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to',
            name='text',
        ),
        migrations.AddField(
            model_name='to',
            name='label',
            field=models.CharField(blank=True, help_text='If label is specified, auto generateed label is replaced to this.', max_length=40, null=True),
        ),
    ]
