# Generated by Django 3.2.14 on 2023-05-27 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0010_rename_to_togroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togroup',
            options={'verbose_name': '宛先グループ', 'verbose_name_plural': '宛先グループ'},
        ),
        migrations.AlterField(
            model_name='togroup',
            name='label',
            field=models.CharField(blank=True, help_text='ここに表示名(ex「全回メーリス」)を指定すると、選択肢としてこの表示名が表示されます。指定がなければ「2018 24期」のように表示されます。', max_length=40, null=True, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='togroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_kaichou', to=settings.AUTH_USER_MODEL, verbose_name='会長'),
        ),
    ]
