name: Deploy to server

on:
  push:
    branches:
      - docker

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      script_stop: true
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        fingerprint: ${{ secrets.SSH_FINGERPRINT }}
        script: |
          git pull
          docker compose -f compose.prod.yaml down
          docker compose -f compose.prod.yaml up --build -d
